# Generated by Django 3.2.4 on 2021-06-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='US/Eastern', max_length=45),
        ),
    ]
