# Generated by Django 3.2.4 on 2021-06-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='post',
        ),
    ]
