# Generated by Django 3.2.4 on 2021-06-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_remove_topic_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(default='Python', on_delete=django.db.models.deletion.CASCADE, related_name='comment_topic', to='blog_app.topic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(default='Python', on_delete=django.db.models.deletion.CASCADE, related_name='posts_topic', to='blog_app.topic'),
            preserve_default=False,
        ),
    ]
